# defmodule TwitchChat.BadgeInfo do
#   @enforce_keys [
#     :badge_info,
#     :badges,
#     :bits,
#     :color,
#     :display_name,
#     :emotes,
#     :id,
#     :mod,
#     :pinned_chat_paid_amount,
#     :pinned_chat_paid_currency,
#     :pinned_chat_paid_exponent,
#     :pinned_chat_paid_level,
#     :pinned_chat_paid_is_system_messsage,
#     :reply_parent_msg_id,
#     :reply_parent_user_id,
#     :reply_parent_display_name,
#     :reply_parent_msg_body,
#     :reply_thread_parent_msg_id,
#     :reply_thread_parent_user_login,
#     :room_id,
#     :subscriber,
#     :tmi_sent_ts,
#     :turbo,
#     :user_id,
#     :user_type,
#     :vip
#   ]
#   defstruct @enforce_keys
#
#   @type t :: %__MODULE__{
#           badge_info: String.t() | nil,
#           badges: String.t() | nil,
#           bits: String.t() | nil,
#           color: String.t() | nil,
#           display_name: String.t() | nil,
#           emotes: String.t() | nil,
#           id: String.t() | nil,
#           mod: String.t() | nil,
#           pinned_chat_paid_amount: String.t() | nil,
#           pinned_chat_paid_currency: String.t() | nil,
#           pinned_chat_paid_exponent: String.t() | nil,
#           pinned_chat_paid_level: String.t() | nil,
#           pinned_chat_paid_is_system_messsage: String.t() | nil,
#           reply_parent_msg_id: String.t() | nil,
#           reply_parent_user_id: String.t() | nil,
#           reply_parent_display_name: String.t() | nil,
#           reply_parent_msg_body: String.t() | nil,
#           reply_thread_parent_msg_id: String.t() | nil,
#           reply_thread_parent_user_login: String.t() | nil,
#           room_id: String.t() | nil,
#           subscriber: String.t() | nil,
#           tmi_sent_ts: String.t() | nil,
#           turbo: String.t() | nil,
#           user_id: String.t() | nil,
#           user_type: String.t() | nil,
#           vip: String.t() | nil
#         }
#
#   def from_map(badge_info_data) do
#     %__MODULE__{
#       badge_info: badge_info_data["badge_info"],
#       badges: badge_info_data["badges"],
#       bits: badge_info_data["bits"],
#       color: badge_info_data["color"],
#       display_name: badge_info_data["display_name"],
#       emotes: badge_info_data["emotes"],
#       id: badge_info_data["id"],
#       mod: badge_info_data["mod"],
#       pinned_chat_paid_amount: badge_info_data["pinned_chat_paid_amount"],
#       pinned_chat_paid_currency: badge_info_data["pinned_chat_paid_currency"],
#       pinned_chat_paid_exponent: badge_info_data["pinned_chat_paid_exponent"],
#       pinned_chat_paid_level: badge_info_data["pinned_chat_paid_level"],
#       pinned_chat_paid_is_system_messsage: badge_info_data["pinned_chat_paid_is_system_messsage"],
#       reply_parent_msg_id: badge_info_data["reply_parent_msg_id"],
#       reply_parent_user_id: badge_info_data["reply_parent_user_id"],
#       reply_parent_display_name: badge_info_data["reply_parent_display_name"],
#       reply_parent_msg_body: badge_info_data["reply_parent_msg_body"],
#       reply_thread_parent_msg_id: badge_info_data["reply_thread_parent_msg_id"],
#       reply_thread_parent_user_login: badge_info_data["reply_thread_parent_user_login"],
#       room_id: badge_info_data["room_id"],
#       subscriber: badge_info_data["subscriber"],
#       tmi_sent_ts: badge_info_data["tmi_sent_ts"],
#       turbo: badge_info_data["turbo"],
#       user_id: badge_info_data["user_id"],
#       user_type: badge_info_data["user_type"],
#       vip: badge_info_data["vip"]
#     }
#   end
# end
